[package]
name = "orbfont"
description = "Orbital font rendering"
repository = "https://github.com/redox-os/orbfont"
version = "0.1.8"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
orbclient = "0.3"
rusttype = "0.2"

[target.'cfg(not(target_os="redox"))'.dependencies]
font-loader = "0.3.2"